### ISSUE TITLE
Readout function in mpnn and mpnn_ggcn

### ISSUE THREAD

**Issue by zeal-up** [priba/nmp_qc#7]
In the original paper, the readout function is different between ggcn and the function used in the paper. But I noticed that you implement them as the same function.
Have I missed something?

**Comment by priba** [comment]
Hi @zeal-github 

In the original paper the authors make use of the set2set network as a Readout. We didn't implement it here and we have used the same proposed in the ggcn. It is in the TODO list https://github.com/priba/nmp_qc/tree/master/models
